---

- name: Generate /etc/chrony.conf
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "/etc/chrony.conf"
    owner: root
    group: root
    mode: "0644"
    backup: true
  register: chrony_conf_result
  when: base_chrony_config is defined

- name: Generate /etc/chrony.keys
  ansible.builtin.template:
    src: chrony.keys.j2
    dest: "/etc/chrony.keys"
    owner: root
    group: root
    mode: "0644"
    backup: true
  register: chrony_keys_result
  when: base_chrony_keys is defined

- name: Restart chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
    enabled: true
    daemon_reload: yes
  when: >
    (chrony_conf_result is defined and chrony_conf_result.changed) or
    (chrony_keys_result is defined and chrony_keys_result.changed)
