---

- name: Ensure cloud-init config directory exists
  ansible.builtin.file:
    path: /etc/cloud/cloud.cfg.d
    state: directory
    mode: '0755'

- name: Set preserve_hostname to true in cloud-init config
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^preserve_hostname:'
    line: 'preserve_hostname: true'
    state: present
    backup: true
  register: cloud_init_result

- name: Remove update_etc_hosts from cloud_init_modules
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^(\s*)-\s*update_etc_hosts\s*$'
    line: '  # - update_etc_hosts'
    backrefs: true
    state: present
  register: update_etc_hosts_result

- name: Restart cloud-init
  ansible.builtin.systemd:
    name: cloud-init
    state: restarted
    enabled: true
    daemon_reload: true
  failed_when: false
  when: >
    (cloud_init_result is defined and cloud_init_result.changed) or
    (update_etc_hosts_result is defined and update_etc_hosts_result.changed)
