---

- name: Gather network facts
  ansible.builtin.setup:
    filter: ansible_default_ipv4

- name: Check if /etc/hosts is accessible
  ansible.builtin.stat:
    path: /etc/hosts
  register: hosts_stat

- name: Update hostname entries in /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
    backup: true
    unsafe_writes: true
  retries: 5
  delay: 1
  register: hosts_update
  until: hosts_update is succeeded
