---

- name: Detect disk type (partition vs whole disk)
  ansible.builtin.set_fact:
    is_partition: "{{ disk.pv | regex_search('[0-9]+$') != none }}"

- name: Extend partition-based disk
  ansible.builtin.include_tasks: grow-partition.yml
  when: is_partition

- name: Create a Volume Group
  community.general.lvg:
    pvresize: true
    pvs: "{{ disk.pv }}"
    vg: "{{ disk.vg }}"
    state: present

- name: Create a Logical Volume
  community.general.lvol:
    vg: "{{ disk.vg }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
    shrink: no
    resizefs: true
  loop: "{{ disk.lv }}"
  loop_control:
    label: "{{ item.name }}"

- name: Make Filesystem
  community.general.filesystem:
    fstype: xfs
    dev: /dev/{{ disk.vg }}/{{ item.name }}
    force: no
  loop: "{{ disk.lv }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create mount point directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  loop: "{{ disk.lv }}"
  loop_control:
    label: "{{ item.path }}"

- name: Mount Filesystem
  ansible.posix.mount:
    src: /dev/{{ disk.vg }}/{{ item.name }}
    path: "{{ item.path }}"
    fstype: xfs
    opts: defaults
    state: mounted
  loop: "{{ disk.lv }}"
  loop_control:
    label: "{{ item.path }}"
