---
# tasks file for role-default-apps

- name: Include base vars
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: install prerequisite packages
  ansible.builtin.include_tasks: "package/{{ ansible_pkg_mgr }}.yml"

- name: disable cloud-init manage_hostname
  ansible.builtin.include_tasks: cloud-init.yml

- name: setup hosts
  ansible.builtin.include_tasks: hosts.yml

- name: setup hostname of the nodes
  ansible.builtin.include_tasks: hostname.yml

- name: disable firewall
  ansible.builtin.include_tasks: firewall.yml

- name: disable swap
  ansible.builtin.include_tasks: swap.yml
  when: base_swap_disabled

- name: disable selinux
  ansible.builtin.include_tasks: selinux.yml
