---
# tasks file for role-default-apps

- name: install prerequisite packages
  ansible.builtin.include_tasks: "package/{{ ansible_pkg_mgr }}.yml"

- name: disable cloud-init manage_hostname
  ansible.builtin.include_tasks: cloud-init.yml

- name: setup hostname
  ansible.builtin.include_tasks: hostname.yml

- name: disable firewall
  ansible.builtin.include_tasks: firewall.yml

- name: disable swap
  ansible.builtin.include_tasks: swap.yml
  when: base_swap_disabled
