---
# tasks file for role_base

- name: Include Base Vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install Prerequisite Packages
  ansible.builtin.include_tasks: "package/{{ ansible_pkg_mgr }}.yml"

- name: Setup Epel-Repo
  ansible.builtin.include_tasks: epel/RedHat.yml
  when: ansible_os_family in ['RedHat']

- name: Install CA Certificate
  ansible.builtin.include_tasks: certificate.yml
  when: base_ca_install_enabled
  tags: notest

- name: Disable Cloud-Init manage_hostname
  ansible.builtin.include_tasks: cloud_init.yml
  when: base_configure_cloud_init
  tags: notest

- name: Setup resolve.conf
  ansible.builtin.include_tasks: resolve.yml
  when: base_resolv_conf_managed
  tags: notest

- name: Setup Hostname of the Nodes
  ansible.builtin.include_tasks: hostname.yml
  when: base_hostname_configured
  tags: notest

- name: Setup Hosts
  ansible.builtin.include_tasks: hosts.yml

- name: Setup Timezone
  ansible.builtin.include_tasks: timezone.yml

- name: Setup Chrony
  ansible.builtin.include_tasks: chronyd.yml

- name: Disable Selinux
  ansible.builtin.include_tasks: selinux.yml

- name: Disable Firewall
  ansible.builtin.include_tasks: firewall.yml

- name: Disable Swap
  ansible.builtin.include_tasks: swap.yml
  when: base_swap_disabled

- name: Setup LVM Disk
  ansible.builtin.include_tasks: lvm.yml
  loop: "{{ base_lvm_disks }}"
  loop_control:
    loop_var: disk
    label: "{{ disk.pv }}"
