---

- name: Create /opt/bin directory if it doesn't exist
  ansible.builtin.file:
    path: /opt/bin
    state: directory
    mode: '0775'
  become: true

- name: Check if mise is already installed
  ansible.builtin.stat:
    path: /opt/bin/mise
  register: mise_binary
  become: true

- name: Install mise to /opt/bin
  ansible.builtin.shell: curl https://mise.run | MISE_INSTALL_PATH=/opt/bin/mise sh
  args:
    creates: /opt/bin/mise
  become: true
  when: not mise_binary.stat.exists

- name: Ensure mise has correct permissions
  ansible.builtin.file:
    path: /opt/bin/mise
    mode: '0775'
  become: true
  when: not mise_binary.stat.exists or ansible_check_mode

- name: Combine base and additional users
  ansible.builtin.set_fact:
    all_mise_users: "{{ base_mise_users + base_mise_additional_users }}"

- name: Add mise activation to users' bashrc
  ansible.builtin.lineinfile:
    path: "{{ item.home }}/.bashrc"
    line: 'eval "$(/opt/bin/mise activate bash)"'
    state: present
    create: "{{ item.username != 'root' }}"
  become: true
  become_user: "{{ item.become_user }}"
  ignore_errors: "{{ item.ignore_errors }}"
  loop: "{{ all_mise_users }}"

- name: Add mise activation to users' profile
  ansible.builtin.lineinfile:
    path: "{{ item.home }}/.profile"
    line: 'eval "$(/opt/bin/mise activate bash)"'
    state: present
    create: true
  become: true
  become_user: "{{ item.become_user }}"
  ignore_errors: "{{ item.ignore_errors }}"
  loop: "{{ all_mise_users }}"
