---
# PyEnv installation and configuration for multiple users
# GitHub: https://github.com/pyenv/pyenv/wiki#suggested-build-environment

# PREPARATION: Get user information and set up environment
- name: Get users' home directories
  ansible.builtin.user:
    name: "{{ item.username }}"
    state: present
  check_mode: true
  register: user_info
  loop: "{{ base_pyenv_python_users | default([]) }}"
  loop_control:
    loop_var: item
    label: "{{ item.username }}"

- name: Create mapping of username to home directory
  ansible.builtin.set_fact:
    pyenv_user_homes: "{{ pyenv_user_homes | default({}) | combine({item.item.username: item.home}) }}"
  loop: "{{ user_info.results }}"
  loop_control:
    label: "{{ item.item.username }}"

# Include the modular tasks
- name: Install and configure PyEnv
  ansible.builtin.include_tasks: pyenv/install.yml

- name: Install and configure PyEnv
  ansible.builtin.include_tasks: pyenv/python.yml

# - name: Install and configure PyEnv
#   ansible.builtin.include_tasks: pyenv/virtualenv.yml

# - name: Install and configure PyEnv
#   ansible.builtin.include_tasks: pyenv/requirements.yml
