---

- name: Disable swap at runtime
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Disable swap permanently (in /etc/fstab)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s.*)$'
    replace: '# \1'
    backup: yes
  register: fstab_swap_disabled
