---
# Apply OS patches/updates for RHEL/Rocky/Fedora (dnf)

- name: Update package cache (dnf)
  ansible.builtin.dnf:
    update_cache: true

- name: Apply all available updates (dnf)
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
    exclude: kernel*
  when: not base_security_updates_only
  register: dnf_update_result

- name: Apply security updates only (dnf)
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
    security: true
    exclude: kernel*
  when: base_security_updates_only
  register: dnf_security_update_result

- name: Update kernel separately (dnf)
  ansible.builtin.dnf:
    name: 'kernel*'
    state: latest
  register: dnf_kernel_update
