---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: role-base-ubuntu2404
    image: ubuntu:24.04
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  inventory:
    host_vars:
      role-base-ubuntu2404:
        ansible_user: root
  playbooks:
    converge: ../resources/converge.yml
  vars:
    base_ca_install_enabled: false
verifier:
  name: ansible
  options:
    playbook: ../resources/verify.yml
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
