---
# Apply security patches using unattended-upgrades method
# This is the recommended method for Ubuntu/Debian

- name: Update package cache (apt)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required packages for security updates
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present
    update_cache: true

- name: Configure unattended-upgrades for security updates only
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: true
  register: unattended_config

- name: Configure unattended-upgrades automatic updates
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Enable unattended-upgrades service
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started

- name: Run dry-run to check available security updates
  ansible.builtin.command: unattended-upgrade --dry-run
  register: security_dry_run
  changed_when: false
  failed_when: false

- name: Check if security updates are available
  ansible.builtin.set_fact:
    security_updates_available: "{{ 'The following packages will be upgraded:' in security_dry_run.stderr or 'Packages that will be upgraded:' in security_dry_run.stderr }}"

- name: Display available security updates
  ansible.builtin.debug:
    msg: "Available security updates found"
  when: security_updates_available

- name: Display no security updates message
  ansible.builtin.debug:
    msg: "No security updates available"
  when: not security_updates_available

- name: Apply security updates using unattended-upgrades
  ansible.builtin.command: unattended-upgrade
  register: apt_security_update_result
  changed_when: 
    - apt_security_update_result.rc == 0
    - security_updates_available
  failed_when: apt_security_update_result.rc != 0 and apt_security_update_result.rc != 1
  when: security_updates_available

- name: Clean up package cache after security updates
  ansible.builtin.apt:
    autoclean: true
