---
name: molecule
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      molecule_scenario:
        description: 'Molecule scenario to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - default
          - ubuntu2404
      python_version:
        description: 'Python version to use'
        required: false
        default: '3.9.23'
        type: choice
        options:
          - '3.9.23'
          - '3.10'
          - '3.11'
          - '3.12'
      debug_mode:
        description: 'Enable debug mode for verbose output'
        required: false
        default: false
        type: boolean

jobs:
  lint:
    name: Lint Syntax Checks
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/ginanck/molecule-almalinux:9-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Download linter configurations
        run: |
          curl -fsSL https://raw.githubusercontent.com/ginanck/shared-pre-commit-hooks/master/config/ansible-lint.yml -o ansible-lint.yml
          curl -fsSL https://raw.githubusercontent.com/ginanck/shared-pre-commit-hooks/master/config/yamllint.yml -o yamllint.yml
          curl -fsSL https://raw.githubusercontent.com/ginanck/shared-pre-commit-hooks/master/config/flake8.conf -o flake8.conf

      - name: Run ansible-lint
        run: |
          ansible-lint -c ansible-lint.yml .

      - name: Run yamllint
        run: |
          yamllint -c yamllint.yml .

      - name: Run flake8
        run: |
          pip3 install flake8
          flake8 --config=flake8.conf .

  molecule:
    name: Molecule Test
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/ginanck/molecule-almalinux:9-latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        scenario: ${{ (github.event.inputs.molecule_scenario || 'all') == 'all' && fromJson('["default", "ubuntu2404"]') || fromJson(format('["{0}"]', github.event.inputs.molecule_scenario || 'all')) }}
    env:
      DOCKER_HOST: 'unix:///var/run/docker.sock'
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Run Molecule tests for ${{ matrix.scenario }} scenario
        run: |
          ansible-galaxy collection install community.docker:4.8.1

          if [ "${{ github.event.inputs.debug_mode }}" == "true" ]; then
            molecule test -s ${{ matrix.scenario }} --debug
          else
            molecule test -s ${{ matrix.scenario }}
          fi
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
