---

- name: Install prerequisites (RedHat family with yum)
  ansible.builtin.yum:
    name:
      - vim
      - bind-utils
      - net-tools
      - tar
      - unzip
      - gzip
    state: present
    update_cache: yes
